meta:
  docker-registry-config: &docker-registry-config
    username: ((docker_cloud_pix4d_user))
    password: ((docker_cloud_pix4d_password))

  s3-resource-simple-git: &s3-resource-simple-git
    uri: https://github.com/Pix4D/s3-resource-simple.git

  gh-status-handlers: &gh-status-handlers
      on_success:
        put: gh-status
        inputs: [s3-resource-simple.git]
        params: {state: success}
      on_failure:
        put: gh-status
        inputs: [s3-resource-simple.git]
        params: {state: failure}
      on_error:
        put: gh-status
        inputs: [s3-resource-simple.git]
        params: {state: error}
      on_abort:
        put: gh-status
        inputs: [s3-resource-simple.git]
        # The GH status API doesn't have "abort", so we use the closest state.
        params:
          state: error

###############################################################################

resource_types:

- name: cogito
  type: registry-image
  check_every: 24h
  source:
    repository: pix4d/cogito
    tag: latest

- name: s3-resource-simple
  type: registry-image
  check_every: 24h
  source:
    <<: *docker-registry-config
    repository: docker.ci.pix4d.com/s3-resource-simple
    tag: ((docker_tag))

###############################################################################

resources:

- name: gh-status
  type: cogito
  check_every: never
  source:
    owner: pix4d
    repo: s3-resource-simple
    access_token: ((github_repo_status_token))
    gchat_webhook: ((gchat_hook))

- name: s3-resource-simple.git
  type: git
  source:
    <<: *s3-resource-simple-git
    branch: ((branch))

- name: s3-resource-simple.docker
  type: registry-image
  source:
    <<: *docker-registry-config
    repository: docker.ci.pix4d.com/s3-resource-simple
    tag: ((docker_tag))

- name: bucket.s3simple
  type: s3-resource-simple
  source:
    bucket: ci-pix4d-concourse-pipeline
    region_name: eu-west-1
    access_key_id: ((concourse_user_access_key))
    secret_access_key: ((concourse_user_secret_key))
    # For this particular pipeline we use the /artifacts paths also for the master branch,
    # so that the files uploaded by the tests will expire and be removed periodically.
    path: artifacts/s3-resource-simple/((branch))/
    # DANGER DANGER DANGER
    # For vast the majority of your use cases, DO NOT enable downloading (do NOT set
    # sync: true)! It will download, on each `get` (explicit and implicit) EVERYTHING
    # in the bucket below the `path` !
    # We enable it only because this pipeline is special: it is testing the resource itself.
    sync: true # DANGER - DO NOT COPY THIS LINE - DANGER
    put_options:
      # copy the source directory recursively.
      - --recursive

###############################################################################

jobs:

- name: build
  <<: *gh-status-handlers
  plan:
  - get: s3-resource-simple.git
    trigger: true
  - put: gh-status
    inputs: [s3-resource-simple.git]
    params: {state: pending}
  - task: build-final-img
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: s3-resource-simple.git
      outputs:
      - name: image
      run:
        path: build
    params:
      CONTEXT: s3-resource-simple.git
      DOCKERFILE: s3-resource-simple.git/Dockerfile
      REGISTRY_MIRRORS: concourse:((concourse_artifactory_password))@dockerhub.ci.pix4d.com
  - put: s3-resource-simple.docker
    inputs: [image, s3-resource-simple.git]
    params:
      image: image/image.tar

- name: test-put
  <<: *gh-status-handlers
  plan:
  - get: s3-resource-simple.git
    trigger: true
    passed: [build]
  - put: gh-status
    inputs: [s3-resource-simple.git]
    params: {state: pending}
  - task: test-put
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      - name: s3-resource-simple.git
      outputs:
      - name: out
      run:
        path: s3-resource-simple.git/ci/tasks/test-put.sh
  - put: bucket.s3simple
    params:
      dir: out

- name: test-get
  <<: *gh-status-handlers
  plan:
  - get: s3-resource-simple.git
    trigger: true
    passed: [test-put]
  - get: bucket.s3simple
    trigger: true
    passed: [test-put]
  - put: gh-status
    inputs: [s3-resource-simple.git]
    params: {state: pending}
  - task: test-get
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      - name: s3-resource-simple.git
      - name: bucket.s3simple
      run:
        path: s3-resource-simple.git/ci/tasks/test-get.sh
